### ISSUE TITLE
Keep Abandoned Vehicle

### ISSUE THREAD

**Issue by RickJamesBish** [Kexanone/ArmaReforgerMods#10]
We have been using this MOD with great success. We use Arma Reforger Server Tool to run out dedicated. Up until the last Reforger patch (v. 1.2.0.124) it has worked without issue. We could shut the server down and choose to load from save next time we played, and the vehicles were all present. Now none of the vehicles are there when return.

Any help appreciated as this is our #1 MOD.

**Comment by Kexanone** [comment]
This mod does not has nothing to do with persistence. It merely ensures that abandoned vehicles don't get deleted by the garbage collector while the scenario is running.
