### ISSUE TITLE
Modify to work with Experimental

### ISSUE THREAD

**Issue by RickJamesBish** [Kexanone/ArmaReforgerMods#12]
Any chance of getting this to work with experimental?

**Comment by Kexanone** [comment]
Which mod are you referring to?

**Comment by RickJamesBish** [comment]
Sorry I thought I had posted in the mods section.. The Keep Abandoned Vehicle Mod
________________________________

**Comment by Kexanone** [comment]
Should be up now.

**Comment by RickJamesBish** [comment]
Thanks. Don't see it though. Will keep checking.
________________________________
