### ISSUE TITLE
Co op on experimental

### ISSUE THREAD

**Issue by Guinness13** [Kexanone/ArmaReforgerMods#13]
Can't exit the hanger. Stuck inside when spawned.

**Comment by Kexanone** [comment]
You don't have to exit the warehouse. The commander can set up an insertion point instead. Just read the field manual entry for COE2 (which also pops up at the start).

**Comment by Guinness13** [comment]
> You don't have to exit the warehouse. The commander can set up an insertion point instead. Just read the field manual entry for COE2 (which also pops up at the start).

Cheers,thank you. 👍
