### ISSUE TITLE
M113 APC doesn't unlock at sergeant level.

### ISSUE THREAD

**Issue by Guide2444** [Kexanone/ArmaReforgerMods#15]
Hello! I was messing around with your mod "M113 APC - Conflict Patch" in a single player conflict session and found that upon reaching Sergeant rank, I was unable to spawn in an M113. It is worth noting that I did stop playing and start playing the session between being Corporal and then being promoted to Sergeant. If you need anymore information let me know!
![20241001202427_1](https://github.com/user-attachments/assets/ed5c4f1f-81ec-478b-84dd-806202f987e5)
![1874880_1520](https://github.com/user-attachments/assets/e444f4d0-0aeb-4a67-abd6-ef9b4aa1dac1)

**Comment by Kexanone** [comment]
This mod is outdated and will be deprecated in future. I made a Pull Request in TheSpaceStrider's repo to directly add it to the M113 mod: SpaceStrider/M113/#2
