### ISSUE TITLE
Server Will Not Load With Medical Notifications Installed

### ISSUE THREAD

**Issue by BaiPiper** [Kexanone/ArmaReforgerMods#3]
Have (had) this mod installed on a dedicated server. Upon restarting the logs state this mod cannot be located in the reforger workshop and shuts down. Server runs by removing the mod. Specifically states cannot locate mod 5EE51BF388E35B44.

**Comment by Kexanone** [comment]
Could you post the exact error message? Reforger's backend was quite unstable the past days, so it could be unrelated to the mod.

**Comment by BaiPiper** [comment]
This is resolved. Deleted the saved addon data from the server for this mod. Restarted server and it ran. Thank you.
