### ISSUE TITLE
Map Marker Menu Fix it doesn't work

### ISSUE THREAD

**Issue by Vafanna** [Kexanone/ArmaReforgerMods#5]
Map Marker Menu Fix it doesn't work since the last update

**Comment by Kexanone** [comment]
The only thing this mod fixes is that you don't get stuck in the bottom right corner of the radial menu when you do 2x LMB the map. This still works for me. Please provide more details and a step by step procedure on how to reproduce your problem.

**Comment by Vafanna** [comment]
Thanks for the reply.
 It seems that I misunderstood the purpose of the mod, the problem is that in your COE2 mission, the radial menu of the marker looks like in the attached image and I can't initiate deployment, and I thought that the mod fixes the radial menu. If the mod fixes the stuck problem, it means that it does what it should, but still I can't deploy in any of the COE2 missions.
Regarding this problem, after spawning in that hangar and trying to choose the deployment point on the map, I cannot do this.

![12](https://github.com/user-attachments/assets/1d632338-488d-4434-a68d-a97d6a7988ea)

**Comment by Kexanone** [comment]
Use RMB instead of 2x LMB for opening the radial context menu rather than the marker placement radial menu.
