### ISSUE TITLE
Kex Escapists Additions LoadOrder ?

### ISSUE THREAD

**Issue by claudejdev** [Kexanone/ArmaReforgerMods#8]
Hey there,

could you please dumb down the requirements to launch [Kex Escapists Additions](https://github.com/Kexanone/ArmaReforgerMods/blob/main/addons/KexEscapistsAdditions) ?

To try it out, I load the dependencies set on the Workshop but can't seem to have the additional effects to show up in GM.

What am I doing wrong ?

Cheers

**Comment by Kexanone** [comment]
Wrong mod. This will be part of GME, but it hasn't been added yet: https://github.com/zen-mod/GME_AR/pull/49
